"""
Kiosk Setup Panel - Cockpit Module
Web tabanlı sunucu yönetim paneli

Özellikler:
- Cockpit kurulumu
- Nginx reverse proxy ile entegrasyon (/cockpit/ path)
- Polkit kuralları (kiosk kullanıcı izinleri)
"""

import json
import os
from typing import Tuple, Dict, Any

from app.modules import register_module
from app.modules.base import BaseModule


@register_module
class CockpitModule(BaseModule):
    name = "cockpit"
    display_name = "Cockpit"
    description = "Web tabanlı sunucu yönetim paneli"
    order = 4
    dependencies = ["network"]
    
    SERVICES_FILE = "/etc/nginx/kiosk-services.json"
    NGINX_CONFIG_FILE = "/etc/nginx/sites-available/kiosk-panel"
    
    def _regenerate_nginx_config(self, services: Dict[str, Any], nginx_port: int) -> None:
        """Nginx config dosyasını servislere göre yeniden oluştur"""
        
        config = f"""# Kiosk Panel - Nginx Reverse Proxy
# Auto-generated by Cockpit module

server {{
    listen {nginx_port};
    server_name localhost;
    add_header X-Content-Type-Options "nosniff" always;
    client_max_body_size 100M;
    proxy_connect_timeout 60;
    proxy_send_timeout 60;
    proxy_read_timeout 60;

"""
        
        for name, service in services.items():
            path = service.get('path', f'/{name}/')
            port = service.get('port', 5000)
            websocket = service.get('websocket', False)
            
            # Root path için trailing slash
            if path == "/":
                config += f"""    # {service.get('display_name', name)}
    location / {{
        proxy_pass http://127.0.0.1:{port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

"""
            elif name == 'cockpit':
                # Cockpit özel yapılandırma - static dosyalar için ayrı location
                config += f"""    # Cockpit static dosyaları
    location /cockpit/static/ {{
        proxy_pass http://127.0.0.1:{port}/cockpit/cockpit/static/;
        proxy_set_header Host $host:$server_port;
    }}

    # Cockpit ana
    location /cockpit/ {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Origin http://localhost:{nginx_port};

        # WebSocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;

        # iframe için
        proxy_hide_header X-Frame-Options;
        proxy_hide_header Content-Security-Policy;
    }}

"""
            else:
                # Diğer servisler
                config += f"""    # {service.get('display_name', name)}
    location {path} {{
        proxy_pass http://127.0.0.1:{port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
"""
                if websocket:
                    config += """        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
"""
                config += "    }\n\n"
        
        config += "}\n"
        
        self.write_file(self.NGINX_CONFIG_FILE, config)
    
    def _register_to_nginx(self) -> bool:
        """Cockpit'i nginx config'e ekle"""
        try:
            nginx_port = self.get_config('nginx.port', 8080)
            cockpit_port = self.get_config('cockpit.port', 9090)
            
            # 1. Services.json'dan mevcut servisleri oku
            services = {}
            if os.path.exists(self.SERVICES_FILE):
                with open(self.SERVICES_FILE, 'r') as f:
                    services = json.load(f)
            
            # 2. Cockpit ekle
            services['cockpit'] = {
                "display_name": "Cockpit",
                "port": cockpit_port,
                "path": "/cockpit/",
                "websocket": True,
                "check_type": "systemd",
                "check_value": "cockpit.socket"
            }
            
            # 3. Services.json'a kaydet
            with open(self.SERVICES_FILE, 'w') as f:
                json.dump(services, f, indent=2)
            
            # 4. Nginx config'i yeniden oluştur
            self._regenerate_nginx_config(services, nginx_port)
            
            # 5. Nginx test ve reload
            result = self.run_command(['/usr/sbin/nginx', '-t'], check=False)
            if result.returncode != 0:
                self.logger.error(f"Nginx config hatası: {result.stderr}")
                return False
            
            self.systemctl('reload', 'nginx')
            
            self.logger.info("Cockpit nginx'e kaydedildi")
            return True
            
        except Exception as e:
            self.logger.error(f"Nginx kayıt hatası: {e}")
            return False
    
    def install(self) -> Tuple[bool, str]:
        """Cockpit kurulumu"""
        try:
            cockpit_port = self.get_config('cockpit.port', 9090)
            nginx_port = self.get_config('nginx.port', 8080)
            
            # =================================================================
            # 1. Cockpit Paketleri
            # =================================================================
            self.logger.info("Cockpit kuruluyor...")
            
            packages = [
                'cockpit',
                'cockpit-system',
                'cockpit-networkmanager',
                'cockpit-storaged',
                'cockpit-packagekit'
            ]
            
            if not self.apt_install(packages):
                return False, "Cockpit paketleri kurulamadı"
            
            # =================================================================
            # 2. Cockpit Yapılandırması (UrlRoot ve Origins)
            # =================================================================
            self.logger.info("Cockpit yapılandırılıyor...")
            
            # Cockpit yapılandırması:
            # - UrlRoot=/cockpit (trailing slash YOK)
            # - Origins hem http hem ws için
            # - AllowEmbedding iframe için gerekli
            cockpit_conf = f"""[WebService]
UrlRoot=/cockpit
Origins = http://localhost:{nginx_port} ws://localhost:{nginx_port}
AllowUnencrypted = true
AllowEmbedding = true

[Session]
IdleTimeout = 0
"""
            
            os.makedirs('/etc/cockpit', exist_ok=True)
            self.write_file('/etc/cockpit/cockpit.conf', cockpit_conf)
            
            # =================================================================
            # 3. Cockpit Socket Etkinleştir
            # =================================================================
            self.systemctl('enable', 'cockpit.socket')
            self.systemctl('start', 'cockpit.socket')
            
            # =================================================================
            # 4. Polkit Kuralları
            # =================================================================
            self.logger.info("Polkit kuralları oluşturuluyor...")
            
            polkit_content = """// NetworkManager izinleri
polkit.addRule(function(action, subject) {
    if (action.id.indexOf("org.freedesktop.NetworkManager") == 0 &&
        subject.user == "kiosk") {
        return polkit.Result.YES;
    }
});

// PackageKit izinleri (sınırlı)
polkit.addRule(function(action, subject) {
    if (action.id.indexOf("org.freedesktop.packagekit") == 0 &&
        subject.user == "kiosk") {
        // Sadece görüntüleme, kurulum değil
        if (action.id == "org.freedesktop.packagekit.system-sources-refresh" ||
            action.id == "org.freedesktop.packagekit.package-info") {
            return polkit.Result.YES;
        }
    }
});
"""
            self.write_file('/etc/polkit-1/rules.d/50-kiosk-network.rules', polkit_content)
            
            # =================================================================
            # 5. Nginx'e Kaydet
            # =================================================================
            self.logger.info("Nginx'e kaydediliyor...")
            if not self._register_to_nginx():
                return False, "Nginx'e kayıt başarısız"
            
            # =================================================================
            # 6. Doğrulama
            # =================================================================
            import time
            time.sleep(2)
            
            result = self.run_command(['systemctl', 'is-active', 'cockpit.socket'], check=False)
            if result.returncode != 0:
                self.logger.warning("Cockpit socket aktif değil, yeniden başlatılıyor...")
                self.systemctl('restart', 'cockpit.socket')
            
            self.logger.info("Cockpit kurulumu tamamlandı")
            return True, "Cockpit kuruldu. Erişim: Servisler sekmesinden"
            
        except Exception as e:
            self.logger.error(f"Cockpit kurulum hatası: {e}")
            return False, str(e)
