#!/bin/bash
# NVIDIA Fallback Script
# Enables nouveau if nvidia module cannot be loaded
# Creates FBDEV rotation config in Secure Boot lockdown state

LOG="/var/log/aco-panel/nvidia-fallback.log"
FBDEV_CONF="/etc/X11/xorg.conf.d/10-fbdev-rotation.conf"

mkdir -p "$(dirname "$LOG")"
mkdir -p "$(dirname "$FBDEV_CONF")"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG"
}

# Create FBDEV rotation config (Secure Boot lockdown fallback)
create_fbdev_config() {
    log "Creating FBDEV rotation config..."
    cat > "$FBDEV_CONF" << 'FBDEV_EOF'
# FBDEV Rotation Configuration (Auto-generated by nvidia-fallback)
# Activates if GPU driver cannot be loaded in Secure Boot lockdown state
Section "Device"
    Identifier "FBDEV"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
    Option "Rotate" "CW"
    Option "ShadowFB" "true"
EndSection
FBDEV_EOF
    log "FBDEV rotation config created"
}

# Delete FBDEV config (not needed if nvidia/nouveau is working)
remove_fbdev_config() {
    if [ -f "$FBDEV_CONF" ]; then
        rm -f "$FBDEV_CONF"
        log "FBDEV rotation config deleted (GPU driver active)"
    fi
}

log "Starting NVIDIA fallback check..."

# Is nvidia module already loaded?
if lsmod | grep -q "^nvidia "; then
    log "NVIDIA module loaded, fallback not needed"
    remove_fbdev_config
    exit 0
fi

# Try if nvidia can be loaded
modprobe nvidia 2>/dev/null
if lsmod | grep -q "^nvidia "; then
    log "NVIDIA module loaded successfully"
    remove_fbdev_config
    exit 0
fi

# nvidia failed to load, enable nouveau
log "NVIDIA failed to load, trying nouveau..."

# Load nouveau (won't work in kernel lockdown even if blacklisted)
modprobe nouveau 2>/dev/null

if lsmod | grep -q "^nouveau "; then
    log "nouveau loaded successfully (NVIDIA fallback)"
    remove_fbdev_config
    # Wait for DRM device to be created
    sleep 2
    if [ -e /dev/dri/card0 ]; then
        log "/dev/dri/card0 exists, GPU ready"
    else
        log "WARNING: /dev/dri/card0 not created"
    fi
    exit 0
fi

# nouveau also failed to load - probably Secure Boot lockdown
log "ERROR: nouveau also failed to load (Secure Boot lockdown?)"
log "FBDEV fallback will be used, rotation provided by Xorg config"

# Create FBDEV rotation config
create_fbdev_config

log "NVIDIA fallback check completed"
