"""
ACO Maintenance Panel - Cockpit Module
Web-based server management panel

Features:
- Cockpit installation
- Nginx reverse proxy integration (/cockpit/ path)
- Polkit rules (kiosk user permissions)
"""

import json
import os
import time
from typing import Tuple, Dict, Any

from app.modules import register_module
from app.modules.base import BaseModule


@register_module
class CockpitModule(BaseModule):
    name = "cockpit"
    display_name = "Cockpit"
    description = "Web-based server management panel"
    order = 4
    dependencies = ["network"]
    
    SERVICES_FILE = "/etc/nginx/aco-services.json"
    NGINX_CONFIG_FILE = "/etc/nginx/sites-available/aco-panel"
    
    def _regenerate_nginx_config(self, services: Dict[str, Any], nginx_port: int) -> None:
        """Regenerate nginx config file based on services"""
        
        config = f"""# ACO Panel - Nginx Reverse Proxy
# Auto-generated by Cockpit module

server {{
    listen {nginx_port};
    server_name localhost;
    add_header X-Content-Type-Options "nosniff" always;
    client_max_body_size 100M;
    proxy_connect_timeout 60;
    proxy_send_timeout 60;
    proxy_read_timeout 60;

"""
        
        for name, service in services.items():
            path = service.get('path', f'/{name}/')
            port = service.get('port', 5000)
            websocket = service.get('websocket', False)
            
            # Trailing slash for root path
            if path == "/":
                config += f"""    # {service.get('display_name', name)}
    location / {{
        proxy_pass http://127.0.0.1:{port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

"""
            elif name == 'cockpit':
                # Cockpit special configuration - separate location for static files
                config += f"""    # Cockpit static files
    location /cockpit/static/ {{
        proxy_pass http://127.0.0.1:{port}/cockpit/cockpit/static/;
        proxy_set_header Host $host:$server_port;
    }}

    # Cockpit main
    location /cockpit/ {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Origin http://localhost:{nginx_port};

        # WebSocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;

        # for iframe
        proxy_hide_header X-Frame-Options;
        proxy_hide_header Content-Security-Policy;
    }}

"""
            else:
                # Other services
                config += f"""    # {service.get('display_name', name)}
    location {path} {{
        proxy_pass http://127.0.0.1:{port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
"""
                if websocket:
                    config += """        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
"""
                # Mechatronic sub_filter (HTML path rewrite)
                if name == 'mechcontroller':
                    config += f"""
        # HTML path rewrite
        sub_filter 'src="/' 'src="{path}';
        sub_filter 'href="/' 'href="{path}';
        sub_filter "src='/" "src='{path}";
        sub_filter "href='/" "href='{path}";
        sub_filter_once off;
        sub_filter_types text/html;
        proxy_set_header Accept-Encoding "";
"""
                config += "    }\n\n"
                
                # Mechatronic root path endpoints (socket.io ve API)
                if name == 'mechcontroller':
                    config += f"""    # Mechatronic socket.io (for root path access)
    location /socket.io/ {{
        proxy_pass http://127.0.0.1:{port}/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
    }}

    # Mechatronic API endpoint
    location = /ip-config {{
        proxy_pass http://127.0.0.1:{port}/ip-config;
        proxy_set_header Host $host;
    }}

"""
        
        config += "}\n"
        
        self.write_file(self.NGINX_CONFIG_FILE, config)
    
    def _register_to_nginx(self) -> bool:
        """Add Cockpit to nginx config"""
        try:
            nginx_port = self.get_config('nginx.port', 4444)
            cockpit_port = self.get_config('cockpit.port', 9090)
            
            # 1. Read existing services from Services.json
            services = {}
            if os.path.exists(self.SERVICES_FILE):
                try:
                    with open(self.SERVICES_FILE, 'r') as f:
                        services = json.load(f)
                except (json.JSONDecodeError, IOError) as e:
                    self.logger.warning(f"Could not read Services.json, will create new: {e}")
                    services = {}
            
            # 2. Add Cockpit
            services['cockpit'] = {
                "display_name": "Cockpit",
                "port": cockpit_port,
                "path": "/cockpit/",
                "websocket": True,
                "check_type": "systemd",
                "check_value": "cockpit.socket"
            }
            
            # 3. Save to Services.json
            with open(self.SERVICES_FILE, 'w') as f:
                json.dump(services, f, indent=2)
            
            # 4. Regenerate Nginx config
            self._regenerate_nginx_config(services, nginx_port)
            
            # 5. Nginx test and reload
            result = self.run_command(['/usr/sbin/nginx', '-t'], check=False)
            if result.returncode != 0:
                self.logger.error(f"Nginx config error: {result.stderr}")
                return False
            
            self.systemctl('reload', 'nginx')
            
            self.logger.info("Cockpit registered to nginx")
            return True
            
        except Exception as e:
            self.logger.error(f"Nginx registration error: {e}")
            return False

    def install(self) -> Tuple[bool, str]:
        """Cockpit installation"""
        try:
            cockpit_port = self.get_config('cockpit.port', 9090)
            nginx_port = self.get_config('nginx.port', 4444)
            
            # =================================================================
            # 1. Cockpit Packages
            # =================================================================
            self.logger.info("Installing Cockpit...")
            
            packages = [
                'cockpit',
                'cockpit-system',
                'cockpit-networkmanager',
                'cockpit-storaged',
                'cockpit-packagekit'
            ]
            
            if not self.apt_install(packages):
                return False, "Could not install Cockpit packages"
            
            # =================================================================
            # 2. Cockpit Configuration (UrlRoot and Origins)
            # =================================================================
            self.logger.info("Configuring Cockpit...")

            # Cockpit configuration:
            # - UrlRoot=/cockpit (NO trailing slash)
            # - Origins for both http and ws
            # - AllowEmbedding required for iframe
            cockpit_conf = f"""[WebService]
UrlRoot=/cockpit
Origins = http://localhost:{nginx_port} ws://localhost:{nginx_port}
AllowUnencrypted = true
AllowEmbedding = true

[Session]
IdleTimeout = 0
"""
            
            os.makedirs('/etc/cockpit', exist_ok=True)
            if not self.write_file('/etc/cockpit/cockpit.conf', cockpit_conf):
                return False, "Could not write Cockpit config"
            
            # =================================================================
            # 3. Enable Cockpit Socket
            # =================================================================
            if not self.systemctl('enable', 'cockpit.socket'):
                self.logger.warning("Could not enable cockpit.socket")
            if not self.systemctl('start', 'cockpit.socket'):
                self.logger.warning("Could not start cockpit.socket")
            
            # =================================================================
            # 4. Polkit Rules
            # =================================================================
            self.logger.info("Creating Polkit rules...")
            
            polkit_content = """// NetworkManager permissions
polkit.addRule(function(action, subject) {
    if (action.id.indexOf("org.freedesktop.NetworkManager") == 0 &&
        subject.user == "kiosk") {
        return polkit.Result.YES;
    }
});

// PackageKit permissions (limited)
polkit.addRule(function(action, subject) {
    if (action.id.indexOf("org.freedesktop.packagekit") == 0 &&
        subject.user == "kiosk") {
        // View only, not install
        if (action.id == "org.freedesktop.packagekit.system-sources-refresh" ||
            action.id == "org.freedesktop.packagekit.package-info") {
            return polkit.Result.YES;
        }
    }
});
"""
            if not self.write_file('/etc/polkit-1/rules.d/50-aco-network.rules', polkit_content):
                self.logger.warning("Could not write Polkit rules")
            
            # =================================================================
            # 5. Register to Nginx
            # =================================================================
            self.logger.info("Registering to Nginx...")
            if not self._register_to_nginx():
                return False, "Nginx registration failed"
            
            # =================================================================
            # 6. Verification
            # =================================================================
            time.sleep(2)
            
            result = self.run_command(['systemctl', 'is-active', 'cockpit.socket'], check=False)
            if result.returncode != 0:
                self.logger.warning("Cockpit socket not active, restarting...")
                self.systemctl('restart', 'cockpit.socket')
            
            self.logger.info("Cockpit installation completed")
            return True, "Cockpit installed. Access from Services tab"

        except Exception as e:
            self.logger.error(f"Cockpit installation error: {e}")
            return False, str(e)
